<a href="https://colab.research.google.com/github/RidaFatima1467/Academy-work/blob/main/Colab_notebook_with_the_8_answers_%2B_code_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**difference loc and iloc?**

**loc[]:**
loc is used to find the certain data from rows and columns labels.


**iloc[]:**
is used to access certain data through integer positions.

**how do you check for and count missing values in DataFrame**

isnull().sum()

**Filter rows where both conditions are true?**

AND(&) operation is used to filter rows because both conditions are true.

**Difference b\w count df.copy() & just assigning df2 = df?**

df.copy():
df.copy is used make a exact copy of dataset.

df2 = df:
in it the dataset which is stored in df is assigned to df2.

In [1]:
import pandas as pd
df= pd.read_csv("/content/tested-selected-columns.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875
...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875

In [3]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583

In [15]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
dtype: int64

**1. Total passenger?**

In [24]:
print("Total passengers:", df.shape[0])

Total passengers: 418

**2. Passenger Survived in Titanic?**

In [20]:
survived= df[df["Survived"]==1]
print(len(survived))

152

**3. how much passenger not survived?**

In [21]:
survived= df[df["Survived"]==0]
print(len(survived))

266

**4. How much female passengers present?**

In [31]:
Female_passengers = df[df["Sex"]=="female"]
print(len(Female_passengers))

152

**5. How much female passengers present?**

In [32]:
male_passengers = df[df["Sex"]=="male"]
print(len(male_passengers))

266

**6. how much young passengers present?**

In [33]:
Young_passengers = df[df["Age"]<=30]
print(len(Young_passengers))

200

**7. Total fare collected?**

In [38]:
total_fare = df["Fare"].sum()
print(total_fare)

14856.5376